const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
(async()=>{
  const browser = await chromium.launch({headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[]; page.on('pageerror', e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:5039/content/23/preview');
  await page.locator('#visual-editor summary').first().click();
  await page.locator('#visual-form [name=title]').fill('A clearer bullet');
  await page.locator('#visual-form [name=caption]').fill('Hypothetical example. Keep only details that are true.');
  await page.locator('[name=before]').fill('Helped with onboarding');
  await page.locator('[name=after]').fill('Maintained the onboarding checklist');
  await page.locator('[name=notes]').fill('Names the work.\nAvoids invented results.');
  await page.getByRole('button',{name:'Preview visual',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('#visual-save').disabled);
  assert.equal(await page.locator('#visual-preview .editorial-visual').count(),1);
  await Promise.all([page.waitForNavigation({waitUntil:'networkidle'}),page.locator('#visual-save').click()]);
  assert.equal(await page.locator('.content-preview-body .editorial-visual').count(),1);
  await page.locator('#visual-editor summary').first().click();
  await page.locator('#visual-target').selectOption('0');
  await page.locator('#visual-form [name=title]').fill('A revised bullet');
  await page.getByRole('button',{name:'Preview visual',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('#visual-save').disabled);
  await Promise.all([page.waitForNavigation({waitUntil:'networkidle'}),page.locator('#visual-save').click()]);
  assert.equal(await page.locator('.editorial-visual h3').textContent(),'A revised bullet');
  await page.setViewportSize({width:390,height:844});
  assert(await page.locator('.editorial-visual').evaluate(el=>el.scrollWidth<=el.clientWidth+1));
  assert.deepEqual(errors,[]);
  await browser.close();
  console.log('Synthetic browser checks passed: add, preview, save, replace, mobile visual layout, no JS errors.');
})().catch(error=>{console.error(error.message);process.exit(1)});
